# Generated by Django 3.0.6 on 2020-08-17 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Workers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Worker_name', models.CharField(default='', max_length=50)),
                ('Worker_address', models.CharField(default='', max_length=70)),
                ('Worker_Phone', models.IntegerField(default=0)),
                ('Worker_email', models.CharField(default='', max_length=50)),
                ('Worker_skills', models.CharField(default='', max_length=100)),
                ('Worker_password', models.CharField(default='', max_length=50)),
                ('date', models.DateField()),
                ('Image', models.ImageField(default='', upload_to='images')),
            ],
        ),
    ]
