# Generated by Django 3.0.6 on 2020-08-17 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workers',
            old_name='Worker_Phone',
            new_name='Phone',
        ),
        migrations.RenameField(
            model_name='workers',
            old_name='Worker_address',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='workers',
            old_name='Worker_email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='workers',
            old_name='Worker_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='workers',
            old_name='Worker_password',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='workers',
            old_name='Worker_skills',
            new_name='skills',
        ),
    ]
